name: Every 10 Minutes schedule

on: [push]
  #schedule:
    #- cron: '0 4 * * *'  # 한국 시간 13:00 (UTC 04:00)
    #- cron: '0 10 * * *' # 한국 시간 19:00 (UTC 10:00)
    

jobs:
  ten_minutes_schedule_job:
    runs-on: ubuntu-latest

    steps:
      - name: Display current time
        run: |
          echo "Current Time"
          echo "UTC   : $(date +"%Y-%m-%dT%H:%M:%SZ")"
          echo "SEOUL : $(TZ=Asia/Seoul date +"%Y-%m-%dT%H:%M:%SZ")"

      - name: Set up Python 3.10
        uses: actions/setup-python@v4  # Python 3.10을 설정합니다.
        with:
          python-version: '3.10'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # pip를 업그레이드합니다.
          python -m pip install requests-html
          python -m pip install urllib3
  
      - name: Run Python Script
        run: |
          python naver_place_serch_ranking_v3.py  # 실제 Python 스크립트 경로로 바꾸세요
